
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

zwave:
    usb_path: /dev/ttyACM0

#sensor:
#  - platform: template
#    sensors:
#        ml_1:
#            friendly_name: "mL 1"
#            unit_of_measurement: 'mL'
#            value_template: "{{ state_attr('sensor.ml_1', 'ml') }}"
#            #value_template: "{{ state_attr('sun.sun', 'elevation') }}"


input_boolean:
    t_wk:
        name: T work lights
        icon: mdi:electric-switch
    cl_wk:
        name: CL work lights
        icon: mdi:electric-switch
    motor1:
        name: Motor 1
        icon: mdi:invert-colors
    motor2:
        name: Motor 2
        icon: mdi:invert-colors
    motor3:
        name: Motor 3
        icon: mdi:invert-colors
    motor4:
        name: Motor 4
        icon: mdi:invert-colors
    motor5:
        name: Motor 5
        icon: mdi:invert-colors
    motor6:
        name: Motor 6
        icon: mdi:invert-colors
    motor3_1:
        name: Motor3 1
        icon: mdi:invert-colors
    motor3_2:
        name: Motor3 2
        icon: mdi:invert-colors
    motor3_3:
        name: Motor3 3
        icon: mdi:invert-colors
    motor3_4:
        name: Motor3 4
        icon: mdi:invert-colors

input_number:
    calibrate_motor1: 
        name: Calibrate Motor 1 
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor2: 
        name: Calibrate Motor 2
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor3: 
        name: Calibrate Motor 3
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor4: 
        name: Calibrate Motor 4
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor5: 
        name: Calibrate Motor 5
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor6: 
        name: Calibrate Motor 6
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    ml_motor1: 
        name: mL Motor 1
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor2: 
        name: mL Motor 2
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor3: 
        name: mL Motor 3
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor4: 
        name: mL Motor 4
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor5: 
        name: mL Motor 5
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor6: 
        name: mL Motor 6
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor3_1: 
        name: mL Motor3 1
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor3_2: 
        name: mL Motor3 2
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor3_3: 
        name: mL Motor3 3
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    ml_motor3_4: 
        name: mL Motor3 4
        initial: 1000
        min: 0.5
        max: 9500
        step: 0.5
        mode: box
    calibrate_motor3_1: 
        name: Calibrate Motor3 1 
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor3_2: 
        name: Calibrate Motor3 2
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor3_3: 
        name: Calibrate Motor3 3
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
    calibrate_motor3_4: 
        name: Calibrate Motor3 4
        initial: 1
        min: 0
        max: 2
        step: 0.01
        mode: box
        
tuya:
  username: tom@contractsoftware.com
  password: Havea6and3
  country_code: 1
        
#logbook:
#  include:
#    entities:
#      - switch.aeon_labs_dsc11_smart_strip_switch
#      - switch.aeon_labs_dsc11_smart_strip_switch_3
#      - switch.aeon_labs_dsc11_smart_strip_switch_4

#lovelace:
#    mode: yaml

#climate:
#  - platform: zwave

#mqtt:
    #broker: 127.0.0.1
    #discovery: true
    #discovery_prefix: <your_discovery_prefix>
    #broker: [YOUR MQTT BROKER] # Remove if you want to use builtin-in MQTT broker
    #birth_message:
        #topic: 'hass/status' # hass/status or homeassistant/status if z2m version >= 4.0.0
        #payload: 'online'
    #will_message:
        #topic: 'hass/status' # or homeassistant/status if z2m version >= 4.0.0
        #payload: 'offline'