views:
  - title: BLUE CL
    path: blue-cl
    badges: []
    cards:
      - type: gauge
        entity: sensor.vpd_09
        min: 0
        max: 2
        needle: true
        unit: kPa
        severity:
          green: 1
          yellow: 0
          red: 1.51
        name: VPD 09
      - type: entities
        entities:
          - entity: sensor.temperature09_1
          - entity: sensor.humidity09_1
          - entity: switch.fan_cl
          - entity: switch.humidifier_09
        show_header_toggle: false
      - type: gauge
        entity: sensor.vpd_17
        min: 0
        max: 2
        needle: true
        unit: kPa
        severity:
          green: 1
          yellow: 0
          red: 1.51
        name: VPD 17 1.0-1.5
      - type: entities
        entities:
          - entity: sensor.temperature_17
          - entity: sensor.humidity_17
          - entity: switch.fan_17
          - entity: switch.humidifier_17
          - entity: switch.dehumidifier_17
          - entity: switch.light_17
          - entity: input_number.hour_lights_on_17
          - entity: input_number.hour_lights_off_17
          - entity: switch.power05_17
          - entity: switch.power06_17
        show_header_toggle: false
      - type: gauge
        entity: sensor.co2_16
        min: 0
        max: 2000
        needle: true
        unit: ppm
        severity:
          green: 1200
          yellow: 0
          red: 1600
        name: co2 device
      - type: entities
        entities:
          - entity: sensor.co2temperature_16
          - entity: sensor.co2humidity_16
      - type: entities
        entities:
          - entity: switch.light_11
          - entity: switch.fan_11
          - entity: sensor.cab_multisensor_temperature
          - entity: sensor.cab_multisensor_relative_humidity
        show_header_toggle: false
        title: CAB-dome
  - title: Blue C
    path: blue-c
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.humidity08_1
          - entity: sensor.temperature08_1
          - entity: switch.power_08
          - entity: sensor.burp_offset_08
        title: TG 11/9
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.humidity06_1
          - entity: sensor.temperature06_1
          - entity: switch.power_06
          - entity: sensor.burp_offset_06
        show_header_toggle: false
        title: CD 11/02
      - type: entities
        entities:
          - entity: sensor.humidity07_1
          - entity: sensor.temperature07_1
        title: ZK Mob7 wHumPk
  - title: Blue
    path: blue
    panel: false
    badges: []
    cards:
      - type: gauge
        entity: sensor.vpd_11
        min: 0
        max: 2
        needle: true
        unit: kPa
        severity:
          green: 0.8
          yellow: 0
          red: 1.01
        name: CAB VPD 0.8-1.0
      - type: entities
        entities:
          - entity: sensor.temperature11
          - entity: switch.fan_11
          - entity: switch.humidifier_11
          - entity: sensor.humidity11
        show_header_toggle: false
      - type: gauge
        entity: sensor.vpd_04
        min: 0
        max: 2
        needle: true
        unit: kPa
        severity:
          green: 1.2
          yellow: 0
          red: 1.61
        name: T VPD 1.2-1.6
      - type: entities
        entities:
          - entity: sensor.temperature04
          - entity: switch.fan_04
          - entity: switch.humidifier_04
          - entity: switch.aeon_labs_dsc11_smart_strip_switch
          - entity: sensor.humidity04
        show_header_toggle: false
      - type: gauge
        entity: sensor.vpd_09
        min: 0
        max: 2
        needle: true
        unit: kPa
        severity:
          green: 1
          yellow: 0
          red: 1.51
        name: CL VPD 1.0-1.5
      - type: entities
        entities:
          - entity: sensor.temperature09_1
          - entity: sensor.humidity09_1
          - entity: switch.fan_cl
          - entity: switch.humidifier_09
          - entity: switch.dehumidifier_09
          - entity: switch.aeon_labs_dsc11_smart_strip_switch_4
          - entity: sensor.temperature_17
          - entity: sensor.humidity_17
        show_header_toggle: false
      - type: entities
        entities:
          - entity: switch.light_11
          - entity: sensor.vpd_11
          - entity: switch.fan_11
          - entity: switch.humidifier_11
          - entity: sensor.temperature11
          - entity: sensor.humidity11
          - entity: sensor.cab_multisensor_temperature
          - entity: sensor.cab_multisensor_relative_humidity
          - entity: input_number.hour_lights_on_cab
          - entity: input_number.hour_lights_off_cab
          - entity: switch.aeon_labs_dsc11_smart_strip_switch_4
        title: 'CAB  (vpd VEG: 0.8-1.0)'
        show_header_toggle: false
        state_color: true
      - type: entities
        entities:
          - entity: binary_sensor.light_status_04
          - entity: sensor.vpd_04
          - entity: switch.fan_04
          - entity: switch.humidifier_04
          - entity: sensor.temperature04
          - entity: sensor.humidity04
          - entity: input_number.hour_lights_on_04
          - entity: input_number.hour_lights_off_04
          - entity: switch.light_04
          - entity: binary_sensor.fan_status_04
          - entity: switch.aeon_labs_dsc11_smart_strip_switch_4
        title: 'T (vpd L.FL: 1.2-1.6)'
        show_header_toggle: false
      - type: entities
        entities:
          - entity: switch.light_cl
          - entity: sensor.vpd_09
          - entity: switch.fan_cl
          - entity: switch.humidifier_09
          - entity: switch.dehumidifier_09
          - entity: sensor.temperature09_1
          - entity: sensor.humidity09_1
          - entity: input_number.hour_lights_on_cl
          - entity: input_number.hour_lights_off_cl
          - entity: sensor.moisture_09_01
          - entity: sensor.moisture_09_02
          - entity: sensor.moisture_09_03
          - entity: sensor.moisture_09_04
          - entity: sensor.moisture_09_05
          - entity: sensor.avg_moisture_09
        title: 'CL (vpd FL: 1.0-1.2)'
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.avg_moisture_13
          - entity: sensor.moisture_13_01
          - entity: sensor.moisture_13_02
        show_header_toggle: false
        title: Upstairs Bedroom
      - type: entities
        entities:
          - entity: binary_sensor.fan_status_02
          - entity: binary_sensor.humidifier_status_02
          - entity: sensor.temperature02
          - entity: sensor.humidity02
          - entity: switch.basement_veggies_switch
        title: BT-Dry
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.vapor_deficit_t
          - entity: sensor.blue_multisensor_t_temperature_2
          - entity: sensor.blue_multisensor_t_relative_humidity_2
        show_header_toggle: false
        title: Cln Dome VPD 0.4-0.8
      - type: entities
        entities:
          - entity: sensor.temperature3_1
          - entity: sensor.humidity3_1
          - entity: sensor.moisture3_3
          - entity: sensor.moisture3_4
        title: Bathroom
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.temperature_08_2
          - entity: sensor.humidity_08_2
          - entity: switch.power_08
          - entity: sensor.on_hour_08
          - entity: sensor.off_hour_08
          - entity: sensor.max_temp_08
          - entity: sensor.max_hum_08
        show_header_toggle: false
        title: AC Control
      - type: entities
        entities:
          - entity: sensor.humidity_1
          - entity: sensor.temperature_1
          - entity: light.blue_motor_1
          - entity: light.blue_motor_2
          - entity: light.blue_motor_3
          - entity: light.blue_motor_4
          - entity: light.blue_motor_5
          - entity: light.blue_motor_6
          - entity: input_boolean.motor1
          - entity: input_number.ml_motor1
          - entity: input_boolean.motor2
          - entity: input_number.ml_motor2
          - entity: input_boolean.motor3
          - entity: input_number.ml_motor3
          - entity: input_boolean.motor4
          - entity: input_number.ml_motor4
          - entity: input_boolean.motor5
          - entity: input_number.ml_motor5
          - entity: input_boolean.motor6
          - entity: input_number.ml_motor6
          - entity: input_number.calibrate_motor1
          - entity: input_number.calibrate_motor2
          - entity: input_number.calibrate_motor3
          - entity: input_number.calibrate_motor4
          - entity: input_number.calibrate_motor5
          - entity: input_number.calibrate_motor6
        title: Mobile
        show_header_toggle: false
      - type: entities
        entities:
          - entity: light.blue_motor3_1
          - entity: light.blue_motor3_2
          - entity: light.blue_motor3_3
          - entity: light.blue_motor3_4
          - entity: input_boolean.motor3_1
          - entity: input_number.ml_motor3_1
          - entity: input_boolean.motor3_2
          - entity: input_number.ml_motor3_2
          - entity: input_boolean.motor3_3
          - entity: input_number.ml_motor3_3
          - entity: input_boolean.motor3_4
          - entity: input_number.ml_motor3_4
          - entity: input_number.calibrate_motor3_1
          - entity: input_number.calibrate_motor3_2
          - entity: input_number.calibrate_motor3_3
          - entity: input_number.calibrate_motor3_4
        title: Mobile 3
        show_header_toggle: false
      - type: entities
        entities:
          - entity: switch.power01_17
          - entity: switch.power02_17
          - entity: switch.power03_17
          - entity: switch.power04_17
          - entity: switch.power05_17
          - entity: switch.power06_17
          - entity: sensor.temperature_17
          - entity: sensor.humidity_17
          - entity: sensor.pressure_17
        show_header_toggle: false
        title: mobile 17
      - type: gauge
        entity: sensor.ccs811_total_volatile_organic_compound
        min: 0
        max: 1000
title: Blue
