esphome:
  name: mobile-21

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1073adad111556b66ab7b537d16e5459"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-21 Fallback Hotspot"
    password: "IhQroVv9b5Ea"

captive_portal:

i2c:
  - id: i2c_sensor
    scl: 22
    sda: 21
    scan: True
    
switch:
  - platform: gpio
    name: "Power_21"
    id: "idpower_21"
    pin: 
      number: 4
      inverted: false
    restore_mode: ALWAYS_OFF
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_21"
      name: "Temperature_21"
    humidity:
      id: "idhumidity_21"
      name: "Humidity_21"
    address: 0x44
    update_interval: 5s