esphome:
  name: blue_cl_floor
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Fennario"
  password: "likeadove"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blue Floor Fallback Hotspot"
    password: "edfmAtP9BWjb"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Light_04"
    id: "idlight_04"
    pin: 2
    restore_mode: ALWAYS_OFF
  - platform: gpio
    name: "Fan_04"
    id: "idfan_04"
    pin: 15
    restore_mode: ALWAYS_OFF