substitutions:
  mobilenum: "11"
  sensor_sda: "21" # "32"
  sensor_scl: "22" # "33"

esphome:
  name: mobile-${mobilenum}
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    
wifi:
  ssid: "Fennario"
  password: "likeadove"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile 11 Fallback Hotspot"
    password: "PP3o7Z1smMti"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

i2c:
- id: i2c_sensor
  sda: ${sensor_sda} #21
  scl: ${sensor_scl} #22
  scan: true
  frequency: 800khz
  timeout: 10ms  
#i2c:
#  - id: i2c_sensor
#    sda: ${sensor_sda}
#    scl: ${sensor_scl}
#    frequency: 800khz
#    scan: True
     
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_${mobilenum}"
      name: "Temperature${mobilenum}"
    humidity:
      id: "idhumidity_${mobilenum}"
      name: "Humidity${mobilenum}"
      accuracy_decimals: 1
    address: 0x44
    update_interval: 3s
 
time:
  - platform: sntp
    id: sntp_time