esphome:
  name: mobile-19
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "284965e0c28b3be0632a2ac630a3e872"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-19 Fallback Hotspot"
    password: "hbgezjOMTFBe"

captive_portal:

i2c:
  - id: i2c_sensor
    scl: 22
    sda: 21
    scan: True
    
switch:
  - platform: gpio
    name: "Power_19"
    id: "idpower_19"
    pin: 
      number: 4
      inverted: true
    restore_mode: ALWAYS_OFF
    
#sensor:
#  - platform: bme280 #bmp280
#    i2c_id: i2c_sensor
#    temperature:
#      id: "idtemperature_19"
#      name: "Temperature_19"
#    humidity:
#      id: "idhumidity_19"
#      name: "Humidity_19"
#    #address: 0x77
#    update_interval: 5s
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_19"
      name: "Temperature_19"
    humidity:
      id: "idhumidity_19"
      name: "Humidity_19"
    address: 0x44
    update_interval: 5s