substitutions:
  mobilenum: "18"
  sensor_sda: "21" # "32"
  sensor_scl: "22" # "33"
  
esphome:
  name: mobile-${mobilenum}
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "e3704b6264924bdeeacf8070e5e9128a"

wifi:
  ssid: "Fennario"
  password: "likeadove"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-18 Fallback Hotspot"
    password: "WtQ0rT5jUcHm"

captive_portal:


i2c:
  - id: i2c_sensor
    sda: ${sensor_sda}
    scl: ${sensor_scl} 
    scan: True

sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_${mobilenum}"
      name: "Temperature${mobilenum}"
    humidity:
      id: "idhumidity_${mobilenum}"
      name: "Humidity${mobilenum}"
      accuracy_decimals: 1
    address: 0x44
    update_interval: 3s