substitutions:
  sonoff_num: "09"
  
esphome:
  name: "power-sonoff-${sonoff_num}"
  #platform: ESP8266
  #board: esp01_1m

esp8266:
  board: esp01_1m
  
#esp8266:
#  board: esp01_1m
#  board_flash_mode: qio
#  restore_from_flash: true
  
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "brDxmyLIFrGY4Xm9LSbTl/+QNyGoHxP5hO/CBjm7Sf0="

ota:
  - platform: esphome
    password: "b6f54c5f93c37b06a3ea587ac23e4777"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.79
    gateway:   192.168.1.1
    subnet:    255.255.255.0
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Sonoff-09 Fallback Hotspot"
    password: "w9JZMd5krAHz"
captive_portal:

#uart:
#  rx_pin: RX
#  baud_rate: 4800

#binary_sensor:
#  - platform: gpio
#    pin:
#      number: GPIO0
#      mode: INPUT_PULLUP
#      inverted: True
#    name: "Button Sonoff ${sonoff_num}"
#    on_press:
#      - switch.toggle: relay
#  - platform: status
#    name: "Status Sonoff ${sonoff_num}"

uart:
  id: uart_bus
  rx_pin: RX        # or GPIO3
  baud_rate: 4800
  parity: EVEN

sensor:
  - platform: cse7766
    uart_id: uart_bus
    energy:
      name: "Energy Sonoff ${sonoff_num}"
      accuracy_decimals: 1
      filters:
        - throttle_average: 30s
    current:
      name: "Current Sonoff ${sonoff_num}"
      accuracy_decimals: 1
      filters:
        - throttle_average: 30s
    voltage:
      name: "Voltage Sonoff ${sonoff_num}"
      accuracy_decimals: 1
      filters:
        - throttle_average: 30s
    power:
      name: "Power Sonoff ${sonoff_num}"
      id: my_power
      accuracy_decimals: 1
      filters:
        - throttle_average: 30s

  - platform: total_daily_energy
    name: "Daily Energy Sonoff ${sonoff_num}"
    accuracy_decimals: 1
    power_id: my_power

switch:
  - platform: gpio
    name: "Switch Sonoff ${sonoff_num}"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

time:
  - platform: sntp
    id: my_time

status_led:
  pin: GPIO13