esphome:
  name: mobile_12
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Fennario"
  password: "likeadove"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile 12 Fallback Hotspot"
    password: "PP3o7Z1smMti"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  - id: i2c_sensor
    sda: 21 #pin6 on right #outer wire
    scl: 22  #pin5 on right
    scan: True
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_12"
      name: "Temperature12"
    humidity:
      id: "idhumidity_12"
      name: "Humidity12"
      accuracy_decimals: 1
    address: 0x44
    update_interval: 30s