esphome:
  name: mobile_04
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Fennario"
  password: "likeadove"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile 04 Fallback Hotspot"
    password: "uoya0sL7qBfA"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


switch:
  - platform: gpio
    name: "Power_04"
    id: "idpower_04"
    pin: 23 #pin15 - top right
    restore_mode: ALWAYS_OFF
    
i2c:
  - id: i2c_sensor
    sda: 16 #pin6 on right #outer wire
    scl: 4  #pin5 on right
    scan: True
  - id: i2c_display
    sda: 22 #pin14  -2nd from top on right
    scl: 1  #pin13  -3rd from top on right
    scan: True


sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature04_1"
      name: "Temperature04_1"
    humidity:
      id: "idhumidity04_1"
      name: "Humidity04_1"
    address: 0x44
    update_interval: 30s

font:
  - file: "Roboto-Regular.ttf"
    id: roboto_regular_font
    size: 20
  - file: "Roboto-Regular.ttf"
    id: roboto_regular_font2
    size: 15
  - file: "Roboto-Regular.ttf"
    id: roboto_regular_font3
    size: 12

globals:
  - id: "is_burping"
    type: bool
    restore_value: no
    initial_value: 'false'
       
time:
  - platform: sntp
    id: sntp_time
    on_time: 
      - seconds: 0
        minutes: /1
        then: # Every 1 minute
          - script.execute: periodic_burp_04
          - script.execute: burpAbove65_04

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    i2c_id: i2c_display
    address: 0x3C
    lambda: |-
      // top center.
      it.printf(64, 0, id(roboto_regular_font), TextAlign::TOP_CENTER, "Mobile 04");
      
      it.printf(0, 40, id(roboto_regular_font3), TextAlign::BASELINE_LEFT, "Smart Burp");
      
      // Print time 
      it.strftime(0, 60, id(roboto_regular_font2), TextAlign::BASELINE_LEFT, "%I:%M %p", id(sntp_time).now());

      // Print humidity
      if (id(idhumidity04_1).has_state()) {
        it.printf(127, 23, id(roboto_regular_font), TextAlign::TOP_RIGHT , "%.1f%%", id(idhumidity04_1).state);
      }

      // Print temperature
      if (id(idtemperature04_1).has_state()) {
        it.printf(120, 60, id(roboto_regular_font), TextAlign::BASELINE_RIGHT , "%.1f°", (id(idtemperature04_1).state * (9.0/5.0) + 32.0));
      }
            
script:
  - id: burpAbove65_04
    then:
      - if:
          condition:
            lambda: "return id(is_burping) == false;"
          then:
            - if:
                condition:
                  switch.is_off: idpower_04
                then:
                  - if:
                      condition:
                        lambda: 'return id(idhumidity04_1).state > 65.0;' #65
                      then:
                        - delay: 2 sec
                        - switch.turn_on: idpower_04
                        - delay: 20 sec
                        - switch.turn_off: idpower_04
                else:
                  - if:
                      condition:
                        lambda: 'return id(idhumidity04_1).state <= 65.0;' #65
                      then:
                        - switch.turn_off: idpower_04
  - id: burp_04
    then:
      - if:
          condition:
            lambda: 'return id(idhumidity04_1).state > 62.0;'
          then:
            - lambda: "id(is_burping) = true;"
            - delay: 2 sec
            - switch.turn_on: idpower_04
            - delay: 15 sec
            - switch.turn_off: idpower_04
            - lambda: "id(is_burping) = false;"
          else:
            - if:
                condition:
                  lambda: 'return id(idhumidity04_1).state > 58.0;'
                then:
                  - lambda: "id(is_burping) = true;"
                  - delay: 1 sec
                  - switch.turn_on: idpower_04
                  - delay: 4 sec
                  - switch.turn_off: idpower_04
                  - lambda: "id(is_burping) = false;"
  - id: periodic_burp_04
    then:
      - if:
          condition: #3x Day 64.0 and above
            lambda: |-
              auto time = id(sntp_time).now();
              return id(idhumidity04_1).state >= 64.0
                && time.second == 0
                && time.minute == 0
                && ( time.hour == 0
                  || time.hour == 8
                  || time.hour == 16 );
          then:
            - script.execute: burp_04
          else:
            - if:
                condition: #1x Day above 63.0 
                  lambda: |-
                    auto time = id(sntp_time).now();
                    return id(idhumidity04_1).state >= 63.0
                      && time.second == 0
                      && time.minute == 0
                      &&   time.hour == 0;
                then:
                  - script.execute: burp_04
                else:
                  - if:
                      condition: #1x Week above 62.0
                        lambda: |-
                          auto time = id(sntp_time).now();
                          return id(idhumidity04_1).state >= 62.0
                            && time.second == 0
                            && time.minute == 0
                            &&   time.hour == 0
                            && time.day_of_week == 1;
                      then:
                        - script.execute: burp_04
                      else:
                        - if:
                            condition: #1x Month 61.0 and above
                              lambda: |-
                                auto time = id(sntp_time).now();
                                return id(idhumidity04_1).state >= 61.0
                                  && time.second == 0
                                  && time.minute == 0
                                  &&   time.hour == 0
                                  && time.day_of_month == 1;
                            then:
                              - script.execute: burp_04
 