substitutions:
  mobilenum: "31"

esphome:
  name: mobile-${mobilenum}
  friendly_name: mobile-${mobilenum}

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GlNxT8nBMQ2obcVkrYkKysoDYRTCwD3a7N8o+TwBdYk="

ota:
  password: "ef90bc92f891a899645788fcc41b9b37"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-31 Fallback Hotspot"
    password: "IepSUpHG4axp"

captive_portal:

i2c:
  - id: i2c_sensor
    scl: 22
    sda: 21
    scan: True
    
switch:
  - platform: gpio
    name: "Power_${mobilenum}"
    id: "idpower_${mobilenum}"
    pin: 
      number: 4
      inverted: true
    restore_mode: ALWAYS_OFF
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_${mobilenum}"
      name: "Temperature_${mobilenum}"
    humidity:
      id: "idhumidity_${mobilenum}"
      name: "Humidity_${mobilenum}"
    address: 0x44
    update_interval: 5s