esphome:
  name: blue_cl
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Fennario"
  password: "likeadove"
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  - id: i2c_sensor
    scl: 22 
    sda: 21 
    scan: True
    
sensor:
  - platform: bme280 #bme280 bmp280
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_cl"
      name: "Temperature_cl"
      oversampling: 16x
    humidity:
      id: "idhumidity_cl"
      name: "Humidity_cl"
      accuracy_decimals: 1
    pressure:
      name: "Pressure_cl"
    address: 0x76 #0x01 #0x76
    update_interval: 30s
    
switch:
  - platform: gpio
    name: "CL_WKlight"
    pin: 15
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "CL_FLlight"
    pin: 2
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "CL_FAN"
    pin: 4
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: 14
    name: A_button
    filters:
      - delayed_off: 250ms

  - platform: gpio
    pin: 27
    name: B_button
    filters:
      - delayed_off: 250ms