esphome:
  name: mobile-19
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "284965e0c28b3be0632a2ac630a3e872"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-19 Fallback Hotspot"
    password: "hbgezjOMTFBe"

captive_portal:

i2c:
  - id: i2c_sensor
    scl: 22
    sda: 21
    scan: True
    
switch:
  - platform: gpio
    name: "Power_19"
    id: "idpower_19"
    pin: 4
    restore_mode: ALWAYS_OFF
    
binary_sensor:
  - platform: gpio
    name: "Water_Sensor_19"
    id: "idwatersensor_19"
    pin: 36
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor
    temperature:
      id: "idtemperature_19"
      name: "Temperature_19"
    humidity:
      id: "idhumidity_19"
      name: "Humidity_19"
    address: 0x44
    update_interval: 5s
  - platform: ultrasonic
    trigger_pin: 13
    echo_pin: 12
    name: "Ultrasonic Sensor 19"
    update_interval: 5s
  - platform: hx711
    name: "HX711 Value"
    dout_pin: 25 #27 #D0
    clk_pin: 26 # 14 #D1
    gain: 128
    accuracy_decimals: 3
    update_interval: 5s
    filters:
      - calibrate_linear:
          - -43913 -> 0
          - 712320 -> 1.316
    unit_of_measurement: kg