substitutions:
  mobilenum: "30"
  sensor_sda: "21"
  sensor_scl: "22"
  
esphome:
  name: mobile-${mobilenum}

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WdWQ2gUM18+ZfeNU1vLqyAz6i7JLwXXhuPWsiv08GEs="

ota:
  password: "fc9b4122f4c17d845478bef149b4ee35"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-30 Fallback Hotspot"
    password: "I5snDyx5k4Ia"

captive_portal:
    
i2c:
  - id: i2c_sensor_${mobilenum}
    sda: ${sensor_sda}
    scl: ${sensor_scl}
    scan: True
    
sensor:
  - platform: sht3xd
    i2c_id: i2c_sensor_${mobilenum}
    temperature:
      id: "idtemperature_${mobilenum}"
      name: "Temperature${mobilenum}"
    humidity:
      id: "idhumidity_${mobilenum}"
      name: "Humidity${mobilenum}"
      accuracy_decimals: 1
    update_interval: 3s
  - platform: template
    name: "VPD ${mobilenum}"
    id: "vpd_${mobilenum}"
    lambda: |-
      float temp = id(idtemperature_${mobilenum}).state;
      float hum  = id(idhumidity_${mobilenum}).state;
      return ((6.1078*exp(17.08085*temp/(234.175+temp)))-(6.1078*exp(17.08085*temp/(234.175+temp))*(hum/100)))/10;
    update_interval: 5s
    unit_of_measurement: "kPa"
    accuracy_decimals: 2