esphome:
  name: mobile-20

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "09f32ae865cc98ce6f65045e2c7ec4e7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mobile-20 Fallback Hotspot"
    password: "NxkUFr6d4A51"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: 13
    echo_pin: 12
    name: "Ultrasonic Sensor 20"
    update_interval: 60s
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - lambda: return 100 * (1.0-( (x-0.05265)/(0.5588-0.05265) ));
    #  - lambda: return 100 * (1.0-(x/0.5588));
      #-- 0.05265