# ──────────────────────────────────────────────────────────────
#  Sonoff Basic (ESP‑01M) – power‑sonoff‑07
#  Schedule: ON  +20 min after sunrise
#            OFF −20 min before sunset
# ──────────────────────────────────────────────────────────────
substitutions:
  sonoff_num: "07"

esphome:
  name: power-sonoff-${sonoff_num}
  friendly_name: power-sonoff-${sonoff_num}

esp8266:
  board: esp01_1m

# ───────────────── SERVICES ─────────────────
logger:

api:
  encryption:
    key: "CTjWPAA9dSecdvuf3Em2kdxqxhU04hUCHOOGKtuBeJE="

ota:
  - platform: esphome
    password: "0342cddccc20d39dbe33cbf03035e35d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Power-Sonoff-${sonoff_num} Fallback Hotspot"
    password: "3uiru8asGGpA"

captive_portal:

# ─────── Real‑time clock (required by sun) ───────
time:
  - platform: sntp
    id: sntp_time
    timezone: "America/New_York"

# ───────────── Sun‑based automation ─────────────
sun:
  latitude: 38.82        # Alexandria, VA  ➜ adjust or use !secret
  longitude: -77.09

  on_sunrise:
    #- offset: "00:20:00"   # 20 min **after** sunrise
    then:
      - logger.log: "Sunrise +20 min → turning relay ON"
      - switch.turn_on: relay

  on_sunset:
    #- offset: "-00:20:00"  # 20 min **before** sunset
    then:
      - logger.log: "Sunset −20 min → turning relay OFF"
      - switch.turn_off: relay

# ───────────── Hardware ─────────────
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button Sonoff ${sonoff_num}"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Status Sonoff ${sonoff_num}"

switch:
  - platform: gpio
    name: "Switch Sonoff ${sonoff_num}"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF

status_led:
  pin: GPIO13