substitutions:
  sonoff_num: "01"
  
esphome:
  name: "power-sonoff-${sonoff_num}"
  platform: ESP8266
  board: esp01_1m


# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: "c6646c837428043d41dde1b825099638"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Sonos-01 Fallback Hotspot"
    password: "XeyrhbnhsZdW"

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    name: "Switch Sonoff ${sonoff_num}"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: my_time

status_led:
  pin: GPIO13