substitutions:
  sonoff_num: "02"
  
esphome:
  name: "power-sonoff-${sonoff_num}"
  platform: ESP8266
  board: esp01_1m
  
#esphome:
#  name: "power-sonoff-01"
#
#esp8266:
#  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  password: "c6646c837428043d41dde1b825099638"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Sonos-01 Fallback Hotspot"
    password: "XeyrhbnhsZdW"

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800
  id: my_uart

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button Sonoff ${sonoff_num}"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Status Sonoff ${sonoff_num}"

sensor:
#  - platform: wifi_signal
#    name: "Sonoff S31 WiFi Signal"
#    update_interval: 60s
  - platform: cse7766
    uart_id: my_uart
    update_interval: 30s
    energy:
      name: "Energy Sonoff ${sonoff_num}"
      accuracy_decimals: 1
    current:
      name: "Current Sonoff ${sonoff_num}"
      accuracy_decimals: 1
    voltage:
      name: "Voltage Sonoff ${sonoff_num}"
      accuracy_decimals: 1
    power:
      name: "Power Sonoff ${sonoff_num}"
      accuracy_decimals: 1
      id: my_power
  - platform: total_daily_energy
    name: "Daily Energy Sonoff ${sonoff_num}"
    power_id: my_power

switch:
  - platform: gpio
    name: "Power Sonoff ${sonoff_num}"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

time:
  - platform: sntp
    id: my_time

status_led:
  pin: GPIO13